name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: fetch
      run: git fetch
    - name: checkout to param branch
      run: git checkout -b param
    - name: Restore dependencies
      run: dotnet restore ./RestaurantTP
    - name: Build
      run: dotnet build ./RestaurantTP --no-restore
    - name: Test
      run: dotnet test ./RestaurantTP --no-build --verbosity normal    
    - name: Deploy
      run: dotnet publish ./RestaurantTP 
    - name: Delete param branch
      run: git branch -D param
